//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLNPrintMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLNPrintMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A impressora já existe.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma impressora cadastrada com esse endereço IP..
        /// </summary>
        internal static string AlreadyExistsBody {
            get {
                return ResourceManager.GetString("AlreadyExistsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a api_command.
        /// </summary>
        internal static string ApiCommand {
            get {
                return ResourceManager.GetString("ApiCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a printer_id.
        /// </summary>
        internal static string ApiId {
            get {
                return ResourceManager.GetString("ApiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a printer_ipv4.
        /// </summary>
        internal static string ApiIpv4 {
            get {
                return ResourceManager.GetString("ApiIpv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a printer_name.
        /// </summary>
        internal static string ApiName {
            get {
                return ResourceManager.GetString("ApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://www.ufrgs.br/cacln/printer/api/.
        /// </summary>
        internal static string ApiUri {
            get {
                return ResourceManager.GetString("ApiUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocupada.
        /// </summary>
        internal static string Buzy {
            get {
                return ResourceManager.GetString("Buzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacidade de .
        /// </summary>
        internal static string CapacityOf {
            get {
                return ResourceManager.GetString("CapacityOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível conectar à internet. Verifique suas configurações de rede..
        /// </summary>
        internal static string ConnectionErrorBody {
            get {
                return ResourceManager.GetString("ConnectionErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha de conexão.
        /// </summary>
        internal static string ConnectionErrorHeader {
            get {
                return ResourceManager.GetString("ConnectionErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ops!.
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Algo não ocorreu como esperado..
        /// </summary>
        internal static string DefaultErrorBody {
            get {
                return ResourceManager.GetString("DefaultErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja excluir a impressora .
        /// </summary>
        internal static string DeleteFormBody {
            get {
                return ResourceManager.GetString("DeleteFormBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://.
        /// </summary>
        internal static string Http {
            get {
                return ResourceManager.GetString("Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ink0 {
            get {
                object obj = ResourceManager.GetObject("ink0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ink100 {
            get {
                object obj = ResourceManager.GetObject("ink100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ink30 {
            get {
                object obj = ResourceManager.GetObject("ink30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ink60 {
            get {
                object obj = ResourceManager.GetObject("ink60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ink90 {
            get {
                object obj = ResourceManager.GetObject("ink90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O endereço IP deve seguir os padrões de formatação..
        /// </summary>
        internal static string IpErrorBody {
            get {
                return ResourceManager.GetString("IpErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço IP inválido.
        /// </summary>
        internal static string IpErrorHeader {
            get {
                return ResourceManager.GetString("IpErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ipv4.
        /// </summary>
        internal static string Ipv4 {
            get {
                return ResourceManager.GetString("Ipv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baixo.
        /// </summary>
        internal static string LowTonerWarning {
            get {
                return ResourceManager.GetString("LowTonerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Print Monitor Agent.
        /// </summary>
        internal static string MonitorAgent {
            get {
                return ResourceManager.GetString("MonitorAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //span[contains(@class,&apos;top_prodname&apos;)].
        /// </summary>
        internal static string NodeQuery {
            get {
                return ResourceManager.GetString("NodeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //td[contains(@class, &apos;statusLine&apos;)].
        /// </summary>
        internal static string NodeStatusQuery {
            get {
                return ResourceManager.GetString("NodeStatusQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //td.
        /// </summary>
        internal static string NodeTd {
            get {
                return ResourceManager.GetString("NodeTd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Print Monitor Agent está rodando em segundo plano..
        /// </summary>
        internal static string NotifyEnabled {
            get {
                return ResourceManager.GetString("NotifyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  necessita de atenção: .
        /// </summary>
        internal static string NotifyIconProblem {
            get {
                return ResourceManager.GetString("NotifyIconProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A impressora .
        /// </summary>
        internal static string NotifyIconText {
            get {
                return ResourceManager.GetString("NotifyIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a está baixo..
        /// </summary>
        internal static string NotifyLow {
            get {
                return ResourceManager.GetString("NotifyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Kit FC baixo.
        /// </summary>
        internal static string NotifyLowFC {
            get {
                return ResourceManager.GetString("NotifyLowFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O kit FC da impressora .
        /// </summary>
        internal static string NotifyLowFCBody {
            get {
                return ResourceManager.GetString("NotifyLowFCBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Kit de manutenção baixo.
        /// </summary>
        internal static string NotifyLowMaintenance {
            get {
                return ResourceManager.GetString("NotifyLowMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O kit de manutenção da impressora .
        /// </summary>
        internal static string NotifyLowMaintenanceBody {
            get {
                return ResourceManager.GetString("NotifyLowMaintenanceBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap offline {
            get {
                object obj = ResourceManager.GetObject("offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  da impressora .
        /// </summary>
        internal static string OfPrinter {
            get {
                return ResourceManager.GetString("OfPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Economiz..
        /// </summary>
        internal static string PowerSaving {
            get {
                return ResourceManager.GetString("PowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problema na impressora.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pronto.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /cgi-bin/dynamic/printer/config/reports/devicestatistics.html.
        /// </summary>
        internal static string ReportUri {
            get {
                return ResourceManager.GetString("ReportUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a error.
        /// </summary>
        internal static string ResponseError {
            get {
                return ResourceManager.GetString("ResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a success.
        /// </summary>
        internal static string ResponseSuccess {
            get {
                return ResourceManager.GetString("ResponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao salvar arquivo..
        /// </summary>
        internal static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar o arquivo. Certifique-se que nenhum outro programa esteja utilizando o mesmo arquivo..
        /// </summary>
        internal static string SaveFileErrorBody {
            get {
                return ResourceManager.GetString("SaveFileErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a secure_key.
        /// </summary>
        internal static string SecureKey {
            get {
                return ResourceManager.GetString("SecureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EAAAAE0pT8ZH3mkkxbhfLPs7kQ2nuOk+TWdbkh/PeHM7a+8T816+kCap4AqQAIzV2i0jHS4pIsLtyJ92emQgTWLW60yqmcrRZD7XQAO3PoEMZzhkpmN/JFwv1e5RRykTsaQWkTRLd2YQSJMz2M8/qyAs+OM=.
        /// </summary>
        internal static string SecureKeyContent {
            get {
                return ResourceManager.GetString("SecureKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  folhas..
        /// </summary>
        internal static string Sheets {
            get {
                return ResourceManager.GetString("Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho .
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /cgi-bin/dynamic/printer/PrinterStatus.html.
        /// </summary>
        internal static string StatusUri {
            get {
                return ResourceManager.GetString("StatusUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /cgi-bin/dynamic/topbar.html.
        /// </summary>
        internal static string TopbarUri {
            get {
                return ResourceManager.GetString("TopbarUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desconhecido.
        /// </summary>
        internal static string UnknownWarning {
            get {
                return ResourceManager.GetString("UnknownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
